### ISSUE TITLE
Lobby chat history does not update initially until you join a lobby slot.

### ISSUE THREAD

**Issue by mwaboff** [TF2Stadium/Frontend#38]
When you join a lobby page, the lobby chat does not update until after you joined a slot. Future messages that are sent while you're considered a "lobby spectator" are received as expected.

------

Video 1: https://www.youtube.com/watch?v=Io0X2IY01-g

In this video I join a lobby page as a spectator. The lobby chat history does not fill in until I join a slot.

--------

Video 2: https://www.youtube.com/watch?v=gGGXnCHCcmM

In this video I had nonagon post in the lobby chat while I was a spectator. As you can see I received his message fine. When I joined a slot, it filled in the chat history after nonagon's message.

------

Video 3: https://www.youtube.com/watch?v=I9y1vv1yJWA

In addition, whenever you join a slot, whether by switching between slots or if you leave the slot and go back, it reputs the entire chat history back into the lobby chat.

**Comment by mwaboff** [comment]
Updated issue to include issue of multiple chat history postings whenever you join a slot.

**Comment by mcapu** [comment]
Right now, all these issues are due to the way the backend handles spectators and players. As for the third one, I created a new issue at https://github.com/TF2Stadium/Helen/issues/72. When that's implemented -or not, I'll make the required changes to the way we keep track of the messages of a lobby.

For the next issues, please create a new one for each bug there is, that way they can be closed individually.

**Comment by mcapu** [comment]
All the bugs were already fixed in different commits.
